# Generated by Django 5.1.4 on 2024-12-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('T', 'Teacher'), ('S', 'Student')], default=('T', 'Teacher'), max_length=1),
        ),
    ]
