# Generated by Django 5.1.4 on 2024-12-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_child_user_alter_customuser_role_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
    ]
