# Generated by Django 5.1.4 on 2024-12-23 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_students'),
        ('users', '0006_remove_teacher_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
