# Generated by Django 5.1.4 on 2024-12-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('category', models.CharField(choices=[('support', 'Техническая поддержка'), ('payment', 'Вопрос по оплате'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Категория')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedback_attachments/', verbose_name='Прикрепленный файл')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В обработке'), ('completed', 'Завершено')], default='new', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
