# Generated by Django 5.1.4 on 2024-12-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
