# Generated by Django 5.1.4 on 2024-12-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_teachers_course_teachers'),
        ('users', '0006_remove_teacher_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses_as_student', to='users.child'),
        ),
    ]
